config/routes.rb
ThreeDPrinting::Application.routes.draw do
  devise_for :users
  resources :designs
  post "search" => "search#index"

  root to: 'welcome#index'

end

app/models/design.rb
class Design < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: {minimum: 4, maximum: 160}
  validates :description, presence: true
  validates :file, presence: true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01} 

  attr_accessible :title, :description, :file

  mount_uploader :file, DesignUploader

  acts_as_indexed :fields => [:title, :description]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  has_many :designs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :set_design, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:edit, :update, :destroy]

  # GET /designs
  def index
    @designs = Design.all
  end

  # GET /designs/1
  def show
  end

  # GET /designs/new
  def new
    @design = Design.new
  end

  # GET /designs/1/edit
  def edit
  end

  # POST /designs
  def create
    @design = Design.new(design_params)
    @design.user_id = current_user
    if @design.save
      redirect_to @design, notice: 'Design was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /designs/1
  def update
    if @design.update(design_params)
      redirect_to @design, notice: 'Design was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /designs/1
  def destroy
    @design.destroy
    redirect_to designs_url, notice: 'Design was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def design_params
      params.require(:design).permit(:title, :description, :file)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @designs = Design.find_with_index(params[:query])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @designs = Design.all.order("download_count DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/designs/_form.html.erb
<%= form_for(@design) do |f| %>
  <% if @design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% @design.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br />
    <%= f.label :description %>
    <%= f.text_area :description %>
    <br />
    <%= f.label :design %>
    <%= f.file_field :file %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designs/edit.html.erb
<h1>Editing design</h1>

<%= render 'form' %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<h1>All Designs</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody data-no-turbolink>
    <% @designs.each do |design| %>
    <tr>
      <td><%= design.title %></td>
      <td><%= link_to 'Show', design %></td>
      <td><%= link_to 'Edit', edit_design_path(design) %></td>
      <td><%= link_to 'Destroy', design, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Design', new_design_path %>

app/views/designs/new.html.erb
<h1>New design</h1>

<%= render 'form' %>

<%= link_to 'Back', designs_path %>

app/views/designs/show.html.erb
    <script>
      $(function() {

        //if ( ! Detector.webgl ) Detector.addGetWebGLMessage();

        var container, stats;
        var HEIGHT = 400;
        var WIDTH = 600;

        var camera, cameraTarget, scene, renderer;

        init();
        animate();

        function init() {

          container = document.createElement( 'div' );
          document.body.appendChild( container );

          camera = new THREE.PerspectiveCamera( 45, WIDTH / HEIGHT, 10, 15000 );
          camera.position.set( 5000, 100, 4000 );

          cameraTarget = new THREE.Vector3( 0, 0, 0 );

          scene = new THREE.Scene();
          scene.fog = new THREE.Fog( 0xffffff, 200, 15000 );

          // Binary files

          var material = new THREE.MeshPhongMaterial( { ambient: 0x0000FF, color: 0x5f5f5f, specular: 0x111111, shininess: 200 } );

          var loader = new THREE.STLLoader();
          loader.addEventListener( 'load', function ( event ) {

            var geometry = event.content;
            var mesh = new THREE.Mesh( geometry, material );

            mesh.position.set( 0, 0, 0 );
            mesh.rotation.set( - Math.PI / 2, 0, 0 );
            //mesh.scale.set( 2, 2, 2 );

            mesh.castShadow = true;
            mesh.receiveShadow = true;

            scene.add( mesh );

          } );
          loader.load( '<%= @design.file.url %>' );

          // Lights

          scene.add( new THREE.AmbientLight( 0x777777 ) );

          addShadowedLight( 1, 1, 1, 0xffffff, 1.35 );
          addShadowedLight( 0.5, 1, -1, 0xffaa00, 1 );

          // renderer

          renderer = new THREE.WebGLRenderer( { antialias: true, alpha: false } );
          renderer.setSize( WIDTH, HEIGHT );

          renderer.setClearColor( scene.fog.color, 1 );

          renderer.gammaInput = true;
          renderer.gammaOutput = true;
          renderer.physicallyBasedShading = true;

          renderer.shadowMapEnabled = true;
          renderer.shadowMapCullFace = THREE.CullFaceBack;

          container.appendChild( renderer.domElement );

          window.addEventListener( 'resize', onWindowResize, false );

        }

        function addShadowedLight( x, y, z, color, intensity ) {

          var directionalLight = new THREE.DirectionalLight( color, intensity );
          directionalLight.position.set( x, y, z )
          scene.add( directionalLight );

          directionalLight.castShadow = true;
          // directionalLight.shadowCameraVisible = true;

          var d = 1;
          directionalLight.shadowCameraLeft = -d;
          directionalLight.shadowCameraRight = d;
          directionalLight.shadowCameraTop = d;
          directionalLight.shadowCameraBottom = -d;

          directionalLight.shadowCameraNear = 1;
          directionalLight.shadowCameraFar = 4;

          directionalLight.shadowMapWidth = 1024;
          directionalLight.shadowMapHeight = 1024;

          directionalLight.shadowBias = -0.005;
          directionalLight.shadowDarkness = 0.15;

        }

        function onWindowResize() {

          camera.aspect = WIDTH / HEIGHT;
          camera.updateProjectionMatrix();

          renderer.setSize( WIDTH, HEIGHT );

        }

        function animate() {

          requestAnimationFrame( animate );

          render();

        }

        function render() {

          var timer = Date.now() * 0.0005;

          camera.position.x = Math.cos( timer ) * 3;
          camera.position.z = Math.sin( timer ) * 3;

          camera.lookAt( cameraTarget );

          renderer.render( scene, camera );

        }


      })
    </script>
<div class = "row">
  <div class="small-4 small-offset-4 rows">
    <h2><%= @design.title %></h2>
  </div>
</div>

<div class = "row">
  <div class="small-4 small-offset-4 rows">
    <p><%= @design.description %></p>
  </div>
</div>

<div class="row">
  <div class="small-4 small-offset-4 rows">
    <p><%= number_to_currency(@design.price) %></p>
  </div>
</div>

<div id="modelviewer">
</div>
<div class = "row">
  <div class="small-4 small-offset-4 rows"><%= link_to 'Download', @design.file.url %> |
<%= link_to 'Edit', edit_design_path(@design) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Shapeshare - 3D Printing Marketplace" %></title>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "three.min.js", "data-turbolinks-eval" => false %>
    <%= javascript_include_tag "stlloader.js", "data-turbolinks-track" => false %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>

  </head>

  <body>
  <nav class="top-bar">
  
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to image_tag("../assets/shapeshare.png", :height => 50, :width=> 125),root_path %></a></h1>
      </li>
    
    </ul>
          
    <section class="top-bar-section">

      <ul class="left">
        <%= form_tag('/search') do %>
          <li class="has-form">
            <%= text_field_tag :query, nil ,:placeholder => "Search for 3D models", :id=>"nav_search_box" %>
          </li>
          <li class="has-form">
            <%= submit_tag 'Search', :class=>"round button", :id=>"nav_search_btn" %>
          </li>
        <% end %>
      </ul>

      <ul class="right">
        <% if user_signed_in? %>
          <li class="divider"></li>
          <li><%= link_to current_user.name, "#" %></a></li>
          <li class="divider"></li>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li class="divider"></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </section>
</nav>

  <%= yield %>
    
  </body>
</html>

app/views/search/index.html.erb
<dl>
  <% @designs.each do |design| %>
    <dt><%= link_to design.title, design_path(design)%></dt>
    <dd><%= design.description %></dd>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<div>
	<div class="small-4 small-offset-4 rows"><h2>Most Downloaded</h2></div>
		<div class="row">
			<ul class="small-block-grid-3">
				<% @designs.each do |design| %>
				<li>
					<div><%= link_to design.title, design_path(design) %></div>
		    		<div><%= link_to image_tag("../assets/thumbnail.png", :height => 50, :width=> 125), design_path(design), class: "th" %></div>
		    	</li>
		    	<% end %>
	    	</ul>
	    </div>
</div>
	